/*
 * Copyright 2015 Jan Kühle
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.juanro.autumandu.data.report;

import androidx.annotation.NonNull;

import lecho.lib.hellocharts.formatter.AxisValueFormatter;
import lecho.lib.hellocharts.model.AxisValue;

/**
 * Base class for axis value formatters with optimized label copying.
 */
public abstract class ReportAxisValueFormatter implements AxisValueFormatter {

    /**
     * Formats the given value as a string.
     * @param value The value to format.
     * @return The formatted string.
     */
    public abstract String format(float value);

    @Override
    public int formatValueForManualAxis(char[] formattedValue, AxisValue axisValue) {
        return copyLabelToFormattedValue(format(axisValue.getValue()), formattedValue);
    }

    @Override
    public int formatValueForAutoGeneratedAxis(char[] formattedValue, float value, int autoDecimalDigits) {
        return copyLabelToFormattedValue(format(value), formattedValue);
    }

    /**
     * Copies the label into the formattedValue array without creating intermediate char arrays.
     * This optimization reduces GC pressure during chart rendering.
     */
    private int copyLabelToFormattedValue(@NonNull String label, char[] formattedValue) {
        int length = Math.min(label.length(), formattedValue.length);

        // Use getChars for zero-allocation copying of characters.
        label.getChars(0, length, formattedValue, formattedValue.length - length);

        return length;
    }
}
